In [2]:
import torch
import torch.nn as nn
import numpy as np
from os.path import join
DATASET_RAW_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/EATD-Corpus"
TRAIN_DATASET_DIR = join(DATASET_RAW_DIR,"train")
VAL_DATASET_DIR = join(DATASET_RAW_DIR,"validation")

NDARRAY_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray"
NDARRAY_TRAIN_DIR = join(NDARRAY_DIR,"train")

In [40]:
emotion_dats_np = np.load(join(NDARRAY_TRAIN_DIR,"emotion_hiddenvec_raw.npz"))["arr_0"]
emotion_dats_np

array([[-0.00729596,  0.00541135, -0.00785628, ...,  0.00705555,
         0.00762028,  0.00584495],
       [-0.00725451,  0.00552307, -0.00774018, ...,  0.00720168,
         0.00811074,  0.00544367],
       [-0.0071334 ,  0.00534694, -0.00800141, ...,  0.00713467,
         0.00805442,  0.00524245],
       ...,
       [-0.00753343,  0.00534807, -0.00919773, ...,  0.00716656,
         0.0082228 ,  0.0060008 ],
       [-0.00733878,  0.00557521, -0.00872992, ...,  0.00721549,
         0.00801547,  0.00622695],
       [-0.00738077,  0.0050772 , -0.00694661, ...,  0.00727519,
         0.00803511,  0.00574921]], dtype=float32)

In [41]:
np.max(emotion_dats_np)

0.8425269

In [42]:
np.min(emotion_dats_np)

-0.83352727

In [43]:
np.isnan(emotion_dats_np).any()

False

In [49]:
np.isinf(emotion_dats_np).any()

False

In [44]:
text_raw_np = np.load(join(NDARRAY_TRAIN_DIR,"text_raw.npz"))["arr_0"]
text_raw_np

array([[ 0.00819601,  0.09847721, -0.01261534, ...,  0.10767291,
        -0.07853799, -0.01072243],
       [ 0.01887482,  0.08961674, -0.01374823, ...,  0.06354537,
        -0.05745608,  0.01751328],
       [ 0.02011874,  0.0690739 , -0.01604566, ...,  0.09700757,
        -0.01609083, -0.01581397],
       ...,
       [ 0.05996604,  0.11375999, -0.00117759, ...,  0.03078397,
        -0.01172958,  0.01353308],
       [ 0.08023878,  0.09977683, -0.00112223, ...,  0.09194035,
        -0.06550316,  0.02254221],
       [ 0.07057535,  0.09971772, -0.0430344 , ...,  0.12040684,
        -0.01996977,  0.05540498]], dtype=float32)

In [45]:
np.max(text_raw_np)

0.20607772

In [46]:
np.min(text_raw_np)

-0.21419512

In [47]:
np.isnan(text_raw_np).any()

False

In [48]:
np.isinf(text_raw_np).any()

False

In [30]:
wavefrom_tf_np = np.load(join(NDARRAY_TRAIN_DIR,"waveform_tf_raw.npz"))["arr_0"]
wavefrom_tf_np

array([[[[-0.03813156, -0.03799292, -0.03839266, ..., -0.0382138 ,
          -0.03826308, -0.03765098],
         [-0.03827494, -0.03791024, -0.03813722, ..., -0.03815002,
          -0.03824893, -0.03771581],
         [-0.03839705, -0.03744366, -0.03879505, ..., -0.03819698,
          -0.03825451, -0.03774103],
         ...,
         [-0.03818484, -0.03814832, -0.03822162, ..., -0.03817864,
          -0.03818599, -0.03821051],
         [-0.0381728 , -0.03814759, -0.03822666, ..., -0.0381813 ,
          -0.03818759, -0.03820935],
         [-0.03819185, -0.03813444, -0.0382302 , ..., -0.03818162,
          -0.0381856 , -0.03821255]],

        [[-0.03819045, -0.03819045, -0.03819045, ..., -0.03819045,
          -0.03819045, -0.03819045],
         [-0.03819045, -0.03838819, -0.03819976, ..., -0.03819811,
          -0.03813362, -0.03809686],
         [-0.03819045, -0.03819017, -0.03785361, ..., -0.03828112,
          -0.03813373, -0.03812637],
         ...,
         [-0.03819045, -0.03819201

In [35]:
np.max(wavefrom_tf_np)

1.0

In [39]:
np.isnan(wavefrom_tf_np).any()

False

In [50]:
np.isinf(wavefrom_tf_np).any()

False

In [32]:
np.min(wavefrom_tf_np)

-1.0

In [33]:
wavefrom_tf_np.shape

(249, 2, 1024, 1024)

In [34]:
wavefrom_tf_np.dtype

dtype('float32')

In [25]:
wavefrom_tf_np = wavefrom_tf_np.astype(np.float32)

In [26]:
wavefrom_tf_np.dtype

dtype('float32')

### 对 waveform_tf 进行 min-max 归一化

In [14]:
min_value = -1
max_value = 1
normalized_array = np.interp(wavefrom_tf_np, (wavefrom_tf_np.min(), wavefrom_tf_np.max()), (min_value, max_value))
normalized_array

array([[[[-0.03813156, -0.03799292, -0.03839266, ..., -0.0382138 ,
          -0.03826308, -0.03765098],
         [-0.03827495, -0.03791024, -0.03813722, ..., -0.03815002,
          -0.03824893, -0.03771581],
         [-0.03839705, -0.03744366, -0.03879505, ..., -0.03819698,
          -0.03825451, -0.03774103],
         ...,
         [-0.03818484, -0.03814832, -0.03822162, ..., -0.03817864,
          -0.03818599, -0.03821051],
         [-0.0381728 , -0.03814759, -0.03822667, ..., -0.0381813 ,
          -0.03818759, -0.03820935],
         [-0.03819185, -0.03813445, -0.0382302 , ..., -0.03818162,
          -0.0381856 , -0.03821255]],

        [[-0.03819045, -0.03819045, -0.03819045, ..., -0.03819045,
          -0.03819045, -0.03819045],
         [-0.03819045, -0.03838819, -0.03819976, ..., -0.03819811,
          -0.03813362, -0.03809686],
         [-0.03819045, -0.03819017, -0.03785361, ..., -0.03828112,
          -0.03813372, -0.03812637],
         ...,
         [-0.03819045, -0.03819201

In [15]:
normalized_array.shape

(249, 2, 1024, 1024)

In [29]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"waveform_tf_raw.npz"),arr_0 = wavefrom_tf_np)