In [1]:
import torch
import torch.nn as nn
import torchaudio
import numpy as np
import os
from os.path import join

In [12]:
DATASET_RAW_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/EATD-Corpus"
TRAIN_DATASET_DIR = join(DATASET_RAW_DIR,"train")
VAL_DATASET_DIR = join(DATASET_RAW_DIR,"validation")
NDARRAY_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray"
NDARRAY_TRAIN_DIR = join(NDARRAY_DIR,"train")
NDARRAY_TEST_DIR = join(NDARRAY_DIR,"test")

In [3]:

dir_list =  os.listdir(VAL_DATASET_DIR)
dir_list = sorted(dir_list, key = int)
dir_list

['2',
 '4',
 '5',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '36',
 '37',
 '39',
 '41',
 '42',
 '43',
 '45',
 '47',
 '48',
 '49',
 '51',
 '52',
 '53',
 '55',
 '56',
 '57',
 '58',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '81',
 '82',
 '83',
 '84',
 '86',
 '87',
 '88',
 '89',
 '90',
 '94',
 '96',
 '97',
 '98',
 '99',
 '103',
 '104',
 '105',
 '106']

In [4]:
waveform_list = []
label_list = []
text_list = []

In [5]:
for dir in dir_list:
    SAMPLE_DIR = join(VAL_DATASET_DIR,dir)
    with open(join(SAMPLE_DIR,"new_label.txt")) as label_file:
        label = label_file.read()
    waveform_1, _ = torchaudio.load(join(SAMPLE_DIR,"negative_out.wav"))
    waveform_2, _ = torchaudio.load(join(SAMPLE_DIR,"neutral_out.wav"))
    waveform_3, _ = torchaudio.load(join(SAMPLE_DIR,"positive_out.wav"))
    if waveform_1.shape[0] > 1:
        waveform_1 = waveform_1[0]
    if waveform_2.shape[0] > 1:
        waveform_2 = waveform_2[0]
    if waveform_3.shape[0] > 1:
        waveform_3 = waveform_3[0]
    
    with open(join(SAMPLE_DIR,"negative.txt")) as text_file:
        text_1 = text_file.read()
        text_list.append(text_1)
    
    with open(join(SAMPLE_DIR,"neutral.txt")) as text_file:
        text_2 = text_file.read()
        text_list.append(text_2)
        
    with open(join(SAMPLE_DIR,"positive.txt")) as text_file:
        text_3 = text_file.read()
        text_list.append(text_3)    
    
    label_list += [label]*3
    waveform_list += [waveform_1,waveform_2,waveform_3]    
    # break

In [6]:
text_list

['生气的时候保持微笑就好了。有那么多情绪要干嘛？情绪是没有用处的东西。\n',
 '未来的话可以考虑当个主播或者职业教围棋什么的。因为这些有意思呀，而且其他的东西就比较麻烦。我是一个比较懒且佛系的人。',
 '喜欢打游戏，因为因为游戏可以带你体验另一个世界，而且还有意思。\n',
 '最近一次不开心，应该是不被别人理解吧，觉得自己辛辛苦苦结果被误解了，就很生气。\n',
 '我不太喜欢小朋友，因为他们太吵了。',
 '最近感到开心的事情就是发了年终奖。\n',
 '我几乎不会失眠，但在失眠时会从绝望变成暴躁。\n',
 '除去一些无意义的消遣之外，我会尝试去学习一些我甚至可能用不到的知识。\n',
 '在放松的时候我最喜欢想象一些我可能可以实现，但可能永远不会去实现的一些设计。主要是因为这些想法会突然之间出现在我的脑海中。\n',
 '很少失眠，因为我瞌睡比较多。\n',
 '喜欢，因为他们非常的纯真天真。\n',
 '寒假放学回家，在爸妈在高铁站接我的时候。\n',
 '我没有经常失眠的这样一个状态，我一般入睡还是比较快的，因为我在入睡之前会做一些让自己比较放松的，让自己去酝酿酝酝酿一下睡意，所以说我不会有经常失眠的那个状态。但是如果是失眠的话，我比较想要自己想要让自己快一点睡着，所以我想要自己睡着那种感觉比较强烈一点。',
 '在未来的话我比较想要从事教师这一个行业，因为我个人的话比较喜欢一个比较稳定的比较（那个）生活步调没有那么紧张的一个生活状态，所以说教师这个职业其实是比较适合我的，再加上我比较恋家是想要花更多时间陪伴我的家人，然后老师的话他其实是可以拥有较多的假期，然后我可以利用这个假期去陪伴我的家人。所以说我觉得教师这一个职业对我来说是比较向往的。',
 '我会玩手机，说为什么？因为我处于很放松的状态的话，其实我不是有很多的事情需要去忙，所以说那就是在我放松的时候，一般是我比较清闲的时候，我清闲的时候就想说刷微博看一下东西，大概就是这个原因。\n',
 '我上一次感到不开心，生气。 懊恼。大概是去年11月初的时候，当时我有投一次国际会议，那时候国际会议出了审稿结果，啊，审稿的结果非常不好啊，有三个审稿人，一个质疑我的贡献不足，一个人认为我的方法提升了不多，另外一个人觉得我我做的东西他根本不理解，唉，真的是，最生气的是有其中一个审稿人，觉得我对文章的理解

In [7]:
for waveform in waveform_list:
    print(waveform.shape)

torch.Size([1, 127520])
torch.Size([1, 288800])
torch.Size([1, 125600])
torch.Size([1, 219040])
torch.Size([1, 44800])
torch.Size([1, 52320])
torch.Size([1, 80640])
torch.Size([1, 90560])
torch.Size([1, 225280])
torch.Size([1, 66720])
torch.Size([1, 84160])
torch.Size([1, 117760])
torch.Size([1, 412000])
torch.Size([1, 552800])
torch.Size([1, 349600])
torch.Size([1, 1039520])
torch.Size([1, 1416800])
torch.Size([1, 837920])
torch.Size([1, 476000])
torch.Size([1, 614720])
torch.Size([1, 546400])
torch.Size([1, 161600])
torch.Size([1, 141280])
torch.Size([1, 55200])
torch.Size([1, 219360])
torch.Size([1, 175520])
torch.Size([1, 144480])
torch.Size([1, 250080])
torch.Size([1, 100800])
torch.Size([1, 233440])
torch.Size([1, 567840])
torch.Size([1, 639840])
torch.Size([1, 230240])
torch.Size([1, 150720])
torch.Size([1, 138080])
torch.Size([1, 199040])
torch.Size([1, 140800])
torch.Size([1, 531040])
torch.Size([1, 293280])
torch.Size([1, 208000])
torch.Size([1, 299360])
torch.Size([1, 146720

In [8]:
len(label_list)

234

### 将 `label_list` 转换成 `ndarray` 并保存

In [9]:
label_np = np.array(label_list)
label_np

array(['55.000000', '55.000000', '55.000000', '26.250000', '26.250000',
       '26.250000', '42.500000', '42.500000', '42.500000', '45.000000',
       '45.000000', '45.000000', '43.750000', '43.750000', '43.750000',
       '41.250000', '41.250000', '41.250000', '41.250000', '41.250000',
       '41.250000', '37.500000', '37.500000', '37.500000', '31.250000',
       '31.250000', '31.250000', '36.250000', '36.250000', '36.250000',
       '36.250000', '36.250000', '36.250000', '47.500000', '47.500000',
       '47.500000', '38.750000', '38.750000', '38.750000', '37.500000',
       '37.500000', '37.500000', '36.250000', '36.250000', '36.250000',
       '52.500000', '52.500000', '52.500000', '50.000000', '50.000000',
       '50.000000', '38.750000', '38.750000', '38.750000', '38.750000',
       '38.750000', '38.750000', '55.000000', '55.000000', '55.000000',
       '31.250000', '31.250000', '31.250000', '55.000000', '55.000000',
       '55.000000', '43.750000', '43.750000', '43.750000', '46.2

In [25]:
label_np.shape

(249,)

In [10]:
label_np = label_np.astype(np.float32)

In [11]:
label_np

array([55.  , 55.  , 55.  , 26.25, 26.25, 26.25, 42.5 , 42.5 , 42.5 ,
       45.  , 45.  , 45.  , 43.75, 43.75, 43.75, 41.25, 41.25, 41.25,
       41.25, 41.25, 41.25, 37.5 , 37.5 , 37.5 , 31.25, 31.25, 31.25,
       36.25, 36.25, 36.25, 36.25, 36.25, 36.25, 47.5 , 47.5 , 47.5 ,
       38.75, 38.75, 38.75, 37.5 , 37.5 , 37.5 , 36.25, 36.25, 36.25,
       52.5 , 52.5 , 52.5 , 50.  , 50.  , 50.  , 38.75, 38.75, 38.75,
       38.75, 38.75, 38.75, 55.  , 55.  , 55.  , 31.25, 31.25, 31.25,
       55.  , 55.  , 55.  , 43.75, 43.75, 43.75, 46.25, 46.25, 46.25,
       37.5 , 37.5 , 37.5 , 48.75, 48.75, 48.75, 46.25, 46.25, 46.25,
       41.25, 41.25, 41.25, 58.75, 58.75, 58.75, 81.25, 81.25, 81.25,
       41.25, 41.25, 41.25, 32.5 , 32.5 , 32.5 , 30.  , 30.  , 30.  ,
       52.5 , 52.5 , 52.5 , 36.25, 36.25, 36.25, 50.  , 50.  , 50.  ,
       50.  , 50.  , 50.  , 41.25, 41.25, 41.25, 30.  , 30.  , 30.  ,
       45.  , 45.  , 45.  , 51.25, 51.25, 51.25, 38.75, 38.75, 38.75,
       47.5 , 47.5 ,

In [13]:
np.savez(join(NDARRAY_TEST_DIR,"labels.npz"),arr_0 = label_np)

### 检查原始 waveform 情况

In [8]:
waveform_list

[tensor([0.0000, 0.0000, 0.0000,  ..., 0.0199, 0.0228, 0.0211]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0960, -0.0858, -0.0795]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0110, -0.0105, -0.0131]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0317, 0.0179, 0.0096]),
 tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0024,  0.0060, -0.0034]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0131, 0.0149, 0.0157]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0088, -0.0119, -0.0098]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0122, 0.0146, 0.0181]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0098, -0.0072, -0.0066]),
 tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.0002]),
 tensor([ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.2736e-02,
         -9.7351e-03,  6.1035e-05]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0031, -0.0082, -0.0168]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0003,  0.0019,  0.0051]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0220, 0.0222, 0.0235]),
 te

In [9]:
max_length_tensor =  max(waveform_list,key=lambda x:x.shape[0])
max_length_tensor

tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0203,  0.0141, -0.0128])

In [10]:
max(max_length_tensor)

tensor(0.8861)

In [9]:
max_length_tensor.shape

torch.Size([1776320])

In [12]:
min_length_tensor = min(waveform_list, key = lambda x:x.shape[0])
min_length_tensor.shape

torch.Size([19488])

In [14]:
print(max(min_length_tensor))
min(min_length_tensor)

tensor(0.9244)


tensor(-0.6523)

In [31]:
n_fft = 2046
hop_length = max_length_tensor.shape[-1] // 1023
result = torch.stft(max_length_tensor,n_fft=2048,hop_length=hop_length, return_complex=True)
result.shape

/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/torch/functional.py:666: UserWarning: A window was not provided. A rectangular window will be applied,which is known to cause spectral leakage. Other windows such as torch.hann_window or torch.hamming_window can are recommended to reduce spectral leakage.To suppress this warning and use a rectangular window, explicitly set `window=torch.ones(n_fft, device=<device>)`. (Triggered internally at /opt/conda/conda-bld/pytorch_1720538440907/work/aten/src/ATen/native/SpectralOps.cpp:836.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]


torch.Size([1025, 1024])

In [12]:
n_fft = 2046
waveform_list_enhance = []
for waveform in waveform_list:
    hop_length = waveform.shape[-1]  // 1023
    waveform_list_enhance.append(torch.stft(waveform, n_fft = n_fft, hop_length= hop_length,return_complex=True)[:,0:1024])


/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/torch/functional.py:666: UserWarning: A window was not provided. A rectangular window will be applied,which is known to cause spectral leakage. Other windows such as torch.hann_window or torch.hamming_window can are recommended to reduce spectral leakage.To suppress this warning and use a rectangular window, explicitly set `window=torch.ones(n_fft, device=<device>)`. (Triggered internally at /opt/conda/conda-bld/pytorch_1720538440907/work/aten/src/ATen/native/SpectralOps.cpp:836.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]


In [13]:
for waveform in waveform_list_enhance:
    print(waveform.shape)

torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])


In [14]:
waveform_list_enhance[0].dtype

torch.complex64

In [15]:
waveform_tf_list = [torch.stack([waveform.real, waveform.imag],dim = 0).numpy() for waveform in waveform_list_enhance]

In [16]:
for waveform in waveform_tf_list:
    print(waveform.shape)

(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024

### 准备将预处理好的数据保存

In [3]:
NDARRAY_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray"
NDARRAY_TRAIN_DIR = join(NDARRAY_DIR,"train")

In [18]:
waveform_tf_raw_np = np.stack(arrays= waveform_tf_list, axis=0)

In [19]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"waveform_tf_raw.npz"),arr_0 = waveform_tf_raw_np)

### 由于 pytorch Dataset 无法装在形状不同的张量，因此将其经过预训练模型预处理后再保存。

#### 心理张量保存

In [12]:
from onnx2torch import convert
import onnx

emotion_model = onnx.load_model(r"/public1/cjh/workspace/DepressionPrediction/model/component/emotion_path/model/model.onnx")
emotion_model = convert(emotion_model)

In [15]:
emotion_model.to("cpu")

GraphModule(
  (ReduceMean_0): OnnxReduceStaticAxes()
  (Sub_1): OnnxBinaryMathOperation()
  (Mul_2): OnnxBinaryMathOperation()
  (ReduceMean_3): OnnxReduceStaticAxes()
  (Sub_4): OnnxBinaryMathOperation()
  (Constant_5): OnnxConstant()
  (Add_6): OnnxBinaryMathOperation()
  (Sqrt_7): OnnxSqrt()
  (Div_8): OnnxBinaryMathOperation()
  (Unsqueeze_9): OnnxUnsqueezeStaticAxes()
  (Conv_10): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
  (Transpose_11): OnnxTranspose()
  (ReduceMean_12): OnnxReduceStaticAxes()
  (Sub_13): OnnxBinaryMathOperation()
  (Constant_14): OnnxConstant()
  (Pow_15): OnnxPow()
  (ReduceMean_16): OnnxReduceStaticAxes()
  (Constant_17): OnnxConstant()
  (Add_18): OnnxBinaryMathOperation()
  (Sqrt_19): OnnxSqrt()
  (Div_20): OnnxBinaryMathOperation()
  (initializers): Module()
  (Mul_21): OnnxBinaryMathOperation()
  (Add_22): OnnxBinaryMathOperation()
  (Transpose_23): OnnxTranspose()
  (Constant_24): OnnxConstant()
  (Div_25): OnnxBinaryMathOperation()
  (Erf_26): On

In [17]:
emotion_hiddenvecotr_list = []
for waveform in waveform_list:
    waveform = torch.unsqueeze(waveform,dim=0)
    emotion_hiddenvecotr_list.append(emotion_model(waveform)[0])
    

: 

In [7]:
data = np.load("/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray/train/emotion_hiddenvec_raw.npz")["arr_0"]
data.shape

(249, 1024)

In [4]:
data = np.squeeze(data)
data.shape

(249, 1024)

In [6]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"emotion_hiddenvec_raw.npz"),arr_0 = data)

### 准备预处理文本向量

In [15]:
from sentence_transformers import SentenceTransformer
sbert =  SentenceTransformer("/public1/cjh/workspace/DepressionPrediction/model/pretrained_model/all-MiniLM-L12-v1",device="cuda:1")

/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [16]:
result = sbert.encode(text_list)

In [17]:
result.shape

(249, 384)

In [18]:
type(result)

numpy.ndarray

In [19]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"text_raw.npz"),arr_0 = result)

In [5]:
label_np = np.load(join(NDARRAY_TRAIN_DIR,"labels.npz"))["arr_0"]

In [7]:
label_np = label_np.astype(np.float32)

In [12]:
label_np.shape

(249, 1)

In [11]:
label_np = np.expand_dims(label_np, axis=-1)

In [13]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"labels.npz"),arr_0 = label_np)