In [1]:
import torch
import torch.nn as nn
import torchaudio
import numpy as np
import os
from os.path import join

In [2]:
DATASET_RAW_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/EATD-Corpus"
TRAIN_DATASET_DIR = join(DATASET_RAW_DIR,"train")
VAL_DATASET_DIR = join(DATASET_RAW_DIR,"validation")
TRAIN_DATASET_DIR

'/public1/cjh/workspace/DepressionPrediction/dataset/EATD-Corpus/train'

In [3]:

dir_list =  os.listdir(TRAIN_DATASET_DIR)
dir_list = sorted(dir_list, key = int)
dir_list

['1',
 '2',
 '3',
 '5',
 '6',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '18',
 '20',
 '21',
 '22',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '51',
 '53',
 '54',
 '55',
 '56',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '66',
 '67',
 '68',
 '69',
 '70',
 '75',
 '76',
 '78',
 '79',
 '81',
 '82',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '93',
 '96',
 '97',
 '99',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '109',
 '111']

In [4]:
waveform_list = []
label_list = []
text_list = []

In [5]:
for dir in dir_list:
    SAMPLE_DIR = join(TRAIN_DATASET_DIR,dir)
    with open(join(SAMPLE_DIR,"new_label.txt")) as label_file:
        label = label_file.read()
    waveform_1, _ = torchaudio.load(join(SAMPLE_DIR,"negative_out.wav"))
    waveform_2, _ = torchaudio.load(join(SAMPLE_DIR,"neutral_out.wav"))
    waveform_3, _ = torchaudio.load(join(SAMPLE_DIR,"positive_out.wav"))
    if waveform_1.shape[0] > 1:
        waveform_1 = waveform_1[0]
    if waveform_2.shape[0] > 1:
        waveform_2 = waveform_2[0]
    if waveform_3.shape[0] > 1:
        waveform_3 = waveform_3[0]
    
    with open(join(SAMPLE_DIR,"negative.txt")) as text_file:
        text_1 = text_file.read()
        text_list.append(text_1)
    
    with open(join(SAMPLE_DIR,"neutral.txt")) as text_file:
        text_2 = text_file.read()
        text_list.append(text_2)
        
    with open(join(SAMPLE_DIR,"positive.txt")) as text_file:
        text_3 = text_file.read()
        text_list.append(text_3)    
    
    label_list += [label]*3
    waveform_list += [waveform_1,waveform_2,waveform_3]    
    # break

In [6]:
text_list

['讨厌的人呢，应该比较讨厌那种，就特别以自我为中心的，要么就是，然后，就什么事情他都觉得自己他很对，然后，特别喜欢和你争论那种人，我特别讨厌。然后，嗯，要不然就是，不太懂得，知道，就人与人之间交往的分寸那样的人我，也挺讨厌的\n',
 '理论上来讲，应该是比较希望能够从事自己喜欢的工作，就是工作的时候能够获得乐趣。嗯，就这个问题我自己也想过。比如说，因为我专业是软工嘛，所以按理来说应该是去编程的，就打代码。嗯，我是不是真的喜欢这个职业呢？我也不是很确定。但是，至少它的薪资应该还\n',
 '嗯，放松的时候，应该最喜欢看，嗯，看电影吧。因为，看电影是一个娱乐性比较强的活动，然后，也不是特别需要动脑子，所以，哎，反正我最近看电影\n',
 '我小学就应该开始学英语的\n',
 '希望从事按时上下班的工作，为什么，为什么呀，为什么呀，为什么，为什么，为什么，为了作息规律一点吧\n',
 '走廊那一头的树是红色的，那一头的树是绿色的\n',
 '就是那种仗着自己，就是性格特别大大咧咧，然后，其实，就是，经常，就是会做一些伤害别人举动的事情',
 '我们家是重组家庭，就是，额，我，我妈妈跟我爸爸离婚了，然后她就给我找了继父，然后我爸那边也，就是，也再婚了，然后我现在是跟妈妈\n',
 '吃的，就比如说，桂林米粉，卷筒粉，烧鸭，烧鹅，柠檬鸭\n',
 '太久远了，不记得了，嘻\n',
 '不喜欢，因为他们很吵，长得又不可爱\n',
 '喜欢睡觉，因为睡觉很舒服\n',
 '最讨厌的人或事情，大概是虚伪的人或者虚伪的事情\n',
 '希望从事一份，薪资可以养得活自己，然后和文化有关的内容。嗯，因为我希望自己不是一天到晚在进行机械的工作，而是能创造一些文化价值\n',
 '嗯，上一次感到开心的时候是上个周末和男朋友一起出去看画展，原因是因为好久都没有这样，就两个人在一起开开心心的，没有什么压力\n',
 '上一次跟别人吵架，可能，一年或半年之前吧。因为什么我也，不太记得了，个人是一个非常不爱跟别人争的人，就，每当遇到问题的时候，就是，我不与谁争，谁与我争我也不屑。我爱大自然，其次是艺术，我手捧着希望之火取暖，火萎了，我也准备走了\n',
 '我的家庭构成比较一般，家里有爸爸和妈妈。额，我没有亲生的兄弟姐妹，然后，姥姥家这边有，有一位大舅，大舅有一个姐姐。然后，爸爸这边有三个，额，

In [7]:
for waveform in waveform_list:
    print(waveform.shape)

torch.Size([429600])
torch.Size([444736])
torch.Size([296576])
torch.Size([31232])
torch.Size([246976])
torch.Size([65376])
torch.Size([194144])
torch.Size([312800])
torch.Size([62976])
torch.Size([33728])
torch.Size([53984])
torch.Size([38080])
torch.Size([117280])
torch.Size([298816])
torch.Size([214592])
torch.Size([480800])
torch.Size([595328])
torch.Size([1190784])
torch.Size([524992])
torch.Size([399968])
torch.Size([198336])
torch.Size([219104])
torch.Size([287936])
torch.Size([180000])
torch.Size([645280])
torch.Size([447264])
torch.Size([1178880])
torch.Size([42240])
torch.Size([512000])
torch.Size([125856])
torch.Size([905664])
torch.Size([272384])
torch.Size([429920])
torch.Size([100352])
torch.Size([147232])
torch.Size([141856])
torch.Size([383040])
torch.Size([293568])
torch.Size([357824])
torch.Size([95552])
torch.Size([135616])
torch.Size([88576])
torch.Size([220128])
torch.Size([184128])
torch.Size([291680])
torch.Size([114816])
torch.Size([49184])
torch.Size([58560])
t

In [8]:
len(label_list)

249

### 将 `label_list` 转换成 `ndarray` 并保存

In [24]:
label_np = np.array(label_list)
label_np

array(['46.250000', '46.250000', '46.250000', '48.750000', '48.750000',
       '48.750000', '56.250000', '56.250000', '56.250000', '62.500000',
       '62.500000', '62.500000', '45.000000', '45.000000', '45.000000',
       '33.750000', '33.750000', '33.750000', '53.750000', '53.750000',
       '53.750000', '37.500000', '37.500000', '37.500000', '47.500000',
       '47.500000', '47.500000', '40.000000', '40.000000', '40.000000',
       '36.250000', '36.250000', '36.250000', '43.750000', '43.750000',
       '43.750000', '42.500000', '42.500000', '42.500000', '46.250000',
       '46.250000', '46.250000', '41.250000', '41.250000', '41.250000',
       '63.750000', '63.750000', '63.750000', '40.000000', '40.000000',
       '40.000000', '62.500000', '62.500000', '62.500000', '61.250000',
       '61.250000', '61.250000', '43.750000', '43.750000', '43.750000',
       '37.500000', '37.500000', '37.500000', '41.250000', '41.250000',
       '41.250000', '41.250000', '41.250000', '41.250000', '60.0

In [25]:
label_np.shape

(249,)

In [75]:
np.savez(join(NDARRAY_TRAIN_DIR,"labels.npz"),arr_0 = label_np)

In [9]:
waveform_list

[tensor([0.0000, 0.0000, 0.0000,  ..., 0.0199, 0.0228, 0.0211]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0960, -0.0858, -0.0795]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0110, -0.0105, -0.0131]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0317, 0.0179, 0.0096]),
 tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0024,  0.0060, -0.0034]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0131, 0.0149, 0.0157]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0088, -0.0119, -0.0098]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0122, 0.0146, 0.0181]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0098, -0.0072, -0.0066]),
 tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.0002]),
 tensor([ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.2736e-02,
         -9.7351e-03,  6.1035e-05]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0031, -0.0082, -0.0168]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0003,  0.0019,  0.0051]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0220, 0.0222, 0.0235]),
 te

In [10]:
max_length_tensor =  max(waveform_list,key=lambda x:x.shape[0])
max_length_tensor

tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0203,  0.0141, -0.0128])

In [11]:
max_length_tensor.shape

torch.Size([1776320])

In [31]:
n_fft = 2046
hop_length = max_length_tensor.shape[-1] // 1023
result = torch.stft(max_length_tensor,n_fft=2048,hop_length=hop_length, return_complex=True)
result.shape

/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/torch/functional.py:666: UserWarning: A window was not provided. A rectangular window will be applied,which is known to cause spectral leakage. Other windows such as torch.hann_window or torch.hamming_window can are recommended to reduce spectral leakage.To suppress this warning and use a rectangular window, explicitly set `window=torch.ones(n_fft, device=<device>)`. (Triggered internally at /opt/conda/conda-bld/pytorch_1720538440907/work/aten/src/ATen/native/SpectralOps.cpp:836.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]


torch.Size([1025, 1024])

In [12]:
n_fft = 2046
waveform_list_enhance = []
for waveform in waveform_list:
    hop_length = waveform.shape[-1]  // 1023
    waveform_list_enhance.append(torch.stft(waveform, n_fft = n_fft, hop_length= hop_length,return_complex=True)[:,0:1024])


/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/torch/functional.py:666: UserWarning: A window was not provided. A rectangular window will be applied,which is known to cause spectral leakage. Other windows such as torch.hann_window or torch.hamming_window can are recommended to reduce spectral leakage.To suppress this warning and use a rectangular window, explicitly set `window=torch.ones(n_fft, device=<device>)`. (Triggered internally at /opt/conda/conda-bld/pytorch_1720538440907/work/aten/src/ATen/native/SpectralOps.cpp:836.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]


In [13]:
for waveform in waveform_list_enhance:
    print(waveform.shape)

torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])


In [14]:
waveform_list_enhance[0].dtype

torch.complex64

In [15]:
waveform_tf_list = [torch.stack([waveform.real, waveform.imag],dim = 0).numpy() for waveform in waveform_list_enhance]

In [16]:
for waveform in waveform_tf_list:
    print(waveform.shape)

(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024

### 准备将预处理好的数据保存

In [17]:
NDARRAY_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray"
NDARRAY_TRAIN_DIR = join(NDARRAY_DIR,"train")

In [18]:
waveform_tf_raw_np = np.stack(arrays= waveform_tf_list, axis=0)

In [19]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"waveform_tf_raw.npz"),arr_0 = waveform_tf_raw_np)

### 由于 pytorch Dataset 无法装在形状不同的张量，因此将其经过预训练模型预处理后再保存。

#### 心理张量保存

In [12]:
from onnx2torch import convert
import onnx

emotion_model = onnx.load_model(r"/public1/cjh/workspace/DepressionPrediction/model/component/emotion_path/model/model.onnx")
emotion_model = convert(emotion_model)

In [15]:
emotion_model.to("cpu")

GraphModule(
  (ReduceMean_0): OnnxReduceStaticAxes()
  (Sub_1): OnnxBinaryMathOperation()
  (Mul_2): OnnxBinaryMathOperation()
  (ReduceMean_3): OnnxReduceStaticAxes()
  (Sub_4): OnnxBinaryMathOperation()
  (Constant_5): OnnxConstant()
  (Add_6): OnnxBinaryMathOperation()
  (Sqrt_7): OnnxSqrt()
  (Div_8): OnnxBinaryMathOperation()
  (Unsqueeze_9): OnnxUnsqueezeStaticAxes()
  (Conv_10): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
  (Transpose_11): OnnxTranspose()
  (ReduceMean_12): OnnxReduceStaticAxes()
  (Sub_13): OnnxBinaryMathOperation()
  (Constant_14): OnnxConstant()
  (Pow_15): OnnxPow()
  (ReduceMean_16): OnnxReduceStaticAxes()
  (Constant_17): OnnxConstant()
  (Add_18): OnnxBinaryMathOperation()
  (Sqrt_19): OnnxSqrt()
  (Div_20): OnnxBinaryMathOperation()
  (initializers): Module()
  (Mul_21): OnnxBinaryMathOperation()
  (Add_22): OnnxBinaryMathOperation()
  (Transpose_23): OnnxTranspose()
  (Constant_24): OnnxConstant()
  (Div_25): OnnxBinaryMathOperation()
  (Erf_26): On

In [17]:
emotion_hiddenvecotr_list = []
for waveform in waveform_list:
    waveform = torch.unsqueeze(waveform,dim=0)
    emotion_hiddenvecotr_list.append(emotion_model(waveform)[0])
    

: 

In [7]:
data = np.load("/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray/train/emotion_hiddenvec_raw.npz")["arr_0"]
data.shape

(249, 1024)

In [4]:
data = np.squeeze(data)
data.shape

(249, 1024)

In [6]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"emotion_hiddenvec_raw.npz"),arr_0 = data)

### 准备预处理文本向量

In [15]:
from sentence_transformers import SentenceTransformer
sbert =  SentenceTransformer("/public1/cjh/workspace/DepressionPrediction/model/pretrained_model/all-MiniLM-L12-v1",device="cuda:1")

/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [16]:
result = sbert.encode(text_list)

In [17]:
result.shape

(249, 384)

In [18]:
type(result)

numpy.ndarray

In [19]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"text_raw.npz"),arr_0 = result)