In [1]:
import torch
import torch.nn as nn
import torchaudio
import numpy as np
import os
from os.path import join

In [2]:
DATASET_RAW_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/EATD-Corpus"
TRAIN_DATASET_DIR = join(DATASET_RAW_DIR,"train")
VAL_DATASET_DIR = join(DATASET_RAW_DIR,"validation")
NDARRAY_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray"
NDARRAY_TRAIN_DIR = join(NDARRAY_DIR,"train")
NDARRAY_TEST_DIR = join(NDARRAY_DIR,"test")

In [4]:
dir_list =  os.listdir(TRAIN_DATASET_DIR)
dir_list = sorted(dir_list, key = int)
dir_list

['1',
 '2',
 '3',
 '5',
 '6',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '18',
 '20',
 '21',
 '22',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '51',
 '53',
 '54',
 '55',
 '56',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '66',
 '67',
 '68',
 '69',
 '70',
 '75',
 '76',
 '78',
 '79',
 '81',
 '82',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '93',
 '96',
 '97',
 '99',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '109',
 '111']

In [21]:
waveform_list = []
label_list = []
text_list = []

### 现在尝试将原始音频也输入

In [22]:
for dir in dir_list:
    SAMPLE_DIR = join(TRAIN_DATASET_DIR,dir)
    with open(join(SAMPLE_DIR,"new_label.txt")) as label_file:
        label = label_file.read()
    waveform_1_raw, _ = torchaudio.load(join(SAMPLE_DIR,"negative.wav"))
    waveform_2_raw, _ = torchaudio.load(join(SAMPLE_DIR,"neutral.wav"))
    waveform_3_raw, _ = torchaudio.load(join(SAMPLE_DIR,"positive.wav"))
    waveform_1, _ = torchaudio.load(join(SAMPLE_DIR,"negative_out.wav"))
    waveform_2, _ = torchaudio.load(join(SAMPLE_DIR,"neutral_out.wav"))
    waveform_3, _ = torchaudio.load(join(SAMPLE_DIR,"positive_out.wav"))
    if waveform_1_raw.shape[0] > 1:
        waveform_1_raw = waveform_1_raw[0]
    if waveform_2_raw.shape[0] > 1:
        waveform_2_raw = waveform_2_raw[0]
    if waveform_3_raw.shape[0] > 1:
        waveform_3_raw = waveform_3_raw[0]
    
    if waveform_1.shape[0] > 1:
        waveform_1 = waveform_1[0]
    if waveform_2.shape[0] > 1:
        waveform_2 = waveform_2[0]
    if waveform_3.shape[0] > 1:
        waveform_3 = waveform_3[0]
    
    with open(join(SAMPLE_DIR,"negative.txt")) as text_file:
        text_1 = text_file.read()
        text_list.append(text_1)
        text_list.append(text_1)
    
    with open(join(SAMPLE_DIR,"neutral.txt")) as text_file:
        text_2 = text_file.read()
        text_list.append(text_2)
        text_list.append(text_2)
        
    with open(join(SAMPLE_DIR,"positive.txt")) as text_file:
        text_3 = text_file.read()
        text_list.append(text_3)    
        text_list.append(text_3)    
    
    label_list += [label]*6
    waveform_list += [waveform_1_raw, waveform_1,waveform_2_raw, waveform_2, waveform_3_raw,waveform_3]    
    # break

In [23]:
len(waveform_list)

498

In [34]:
torch.max(torch.tensor([torch.max(x).item() for x in waveform_list]))

tensor(1.0000)

In [33]:
torch.min(torch.tensor([torch.min(x).item() for x in waveform_list]))

tensor(-1.)

In [37]:
label_list_np = np.array(label_list,dtype = np.float32)
label_list_np.shape

(498,)

In [38]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"label_expand.npz"),arr_0 = label_list_np)

In [54]:
label_list_np = np.load(join(NDARRAY_TEST_DIR,"labels.npz"))["arr_0"]
label_list_np.shape

(234, 1)

In [55]:
label_list_bi = [1 if x >=53 else 0 for x in label_list_np ]

In [56]:
label_list_bi = np.array(label_list_bi,dtype= np.int8)

In [60]:
np.savez_compressed(join(NDARRAY_TEST_DIR,"label_expand_bi.npz"),arr_0 = label_list_bi)


In [58]:
label_list_bi = np.expand_dims(label_list_bi, axis=1)

In [59]:
label_list_bi.shape

(234, 1)

In [13]:
label_list_saved = np.load("/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray/train/labels.npz")["arr_0"]
label_list_saved.shape

(249, 1)

In [16]:
label_list_np = np.array(label_list,dtype = np.float32)
label_list_np = np.expand_dims(label_list_np, axis=1)
label_list_np.shape

(249, 1)

In [17]:
np.sum(label_list_np ==label_list_saved)

249

In [7]:
for waveform in waveform_list:
    print(waveform.shape)

torch.Size([1, 127520])
torch.Size([1, 288800])
torch.Size([1, 125600])
torch.Size([1, 219040])
torch.Size([1, 44800])
torch.Size([1, 52320])
torch.Size([1, 80640])
torch.Size([1, 90560])
torch.Size([1, 225280])
torch.Size([1, 66720])
torch.Size([1, 84160])
torch.Size([1, 117760])
torch.Size([1, 412000])
torch.Size([1, 552800])
torch.Size([1, 349600])
torch.Size([1, 1039520])
torch.Size([1, 1416800])
torch.Size([1, 837920])
torch.Size([1, 476000])
torch.Size([1, 614720])
torch.Size([1, 546400])
torch.Size([1, 161600])
torch.Size([1, 141280])
torch.Size([1, 55200])
torch.Size([1, 219360])
torch.Size([1, 175520])
torch.Size([1, 144480])
torch.Size([1, 250080])
torch.Size([1, 100800])
torch.Size([1, 233440])
torch.Size([1, 567840])
torch.Size([1, 639840])
torch.Size([1, 230240])
torch.Size([1, 150720])
torch.Size([1, 138080])
torch.Size([1, 199040])
torch.Size([1, 140800])
torch.Size([1, 531040])
torch.Size([1, 293280])
torch.Size([1, 208000])
torch.Size([1, 299360])
torch.Size([1, 146720

In [8]:
len(label_list)

234

### 将 `label_list` 转换成 `ndarray` 并保存

In [9]:
label_np = np.array(label_list)
label_np

array(['55.000000', '55.000000', '55.000000', '26.250000', '26.250000',
       '26.250000', '42.500000', '42.500000', '42.500000', '45.000000',
       '45.000000', '45.000000', '43.750000', '43.750000', '43.750000',
       '41.250000', '41.250000', '41.250000', '41.250000', '41.250000',
       '41.250000', '37.500000', '37.500000', '37.500000', '31.250000',
       '31.250000', '31.250000', '36.250000', '36.250000', '36.250000',
       '36.250000', '36.250000', '36.250000', '47.500000', '47.500000',
       '47.500000', '38.750000', '38.750000', '38.750000', '37.500000',
       '37.500000', '37.500000', '36.250000', '36.250000', '36.250000',
       '52.500000', '52.500000', '52.500000', '50.000000', '50.000000',
       '50.000000', '38.750000', '38.750000', '38.750000', '38.750000',
       '38.750000', '38.750000', '55.000000', '55.000000', '55.000000',
       '31.250000', '31.250000', '31.250000', '55.000000', '55.000000',
       '55.000000', '43.750000', '43.750000', '43.750000', '46.2

In [25]:
label_np.shape

(249,)

In [10]:
label_np = label_np.astype(np.float32)

In [11]:
label_np

array([55.  , 55.  , 55.  , 26.25, 26.25, 26.25, 42.5 , 42.5 , 42.5 ,
       45.  , 45.  , 45.  , 43.75, 43.75, 43.75, 41.25, 41.25, 41.25,
       41.25, 41.25, 41.25, 37.5 , 37.5 , 37.5 , 31.25, 31.25, 31.25,
       36.25, 36.25, 36.25, 36.25, 36.25, 36.25, 47.5 , 47.5 , 47.5 ,
       38.75, 38.75, 38.75, 37.5 , 37.5 , 37.5 , 36.25, 36.25, 36.25,
       52.5 , 52.5 , 52.5 , 50.  , 50.  , 50.  , 38.75, 38.75, 38.75,
       38.75, 38.75, 38.75, 55.  , 55.  , 55.  , 31.25, 31.25, 31.25,
       55.  , 55.  , 55.  , 43.75, 43.75, 43.75, 46.25, 46.25, 46.25,
       37.5 , 37.5 , 37.5 , 48.75, 48.75, 48.75, 46.25, 46.25, 46.25,
       41.25, 41.25, 41.25, 58.75, 58.75, 58.75, 81.25, 81.25, 81.25,
       41.25, 41.25, 41.25, 32.5 , 32.5 , 32.5 , 30.  , 30.  , 30.  ,
       52.5 , 52.5 , 52.5 , 36.25, 36.25, 36.25, 50.  , 50.  , 50.  ,
       50.  , 50.  , 50.  , 41.25, 41.25, 41.25, 30.  , 30.  , 30.  ,
       45.  , 45.  , 45.  , 51.25, 51.25, 51.25, 38.75, 38.75, 38.75,
       47.5 , 47.5 ,

In [13]:
np.savez(join(NDARRAY_TEST_DIR,"labels.npz"),arr_0 = label_np)

### 检查原始 waveform 情况

In [8]:
waveform_list

[tensor([0.0000, 0.0000, 0.0000,  ..., 0.0199, 0.0228, 0.0211]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0960, -0.0858, -0.0795]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0110, -0.0105, -0.0131]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0317, 0.0179, 0.0096]),
 tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0024,  0.0060, -0.0034]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0131, 0.0149, 0.0157]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0088, -0.0119, -0.0098]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0122, 0.0146, 0.0181]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0098, -0.0072, -0.0066]),
 tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.0002]),
 tensor([ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.2736e-02,
         -9.7351e-03,  6.1035e-05]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0031, -0.0082, -0.0168]),
 tensor([ 0.0000,  0.0000,  0.0000,  ..., -0.0003,  0.0019,  0.0051]),
 tensor([0.0000, 0.0000, 0.0000,  ..., 0.0220, 0.0222, 0.0235]),
 te

In [9]:
max_length_tensor =  max(waveform_list,key=lambda x:x.shape[0])
max_length_tensor

tensor([ 0.0000,  0.0000,  0.0000,  ...,  0.0203,  0.0141, -0.0128])

In [10]:
max(max_length_tensor)

tensor(0.8861)

In [9]:
max_length_tensor.shape

torch.Size([1776320])

In [12]:
min_length_tensor = min(waveform_list, key = lambda x:x.shape[0])
min_length_tensor.shape

torch.Size([19488])

In [14]:
print(max(min_length_tensor))
min(min_length_tensor)

tensor(0.9244)


tensor(-0.6523)

In [31]:
n_fft = 2046
hop_length = max_length_tensor.shape[-1] // 1023
result = torch.stft(max_length_tensor,n_fft=2048,hop_length=hop_length, return_complex=True)
result.shape

/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/torch/functional.py:666: UserWarning: A window was not provided. A rectangular window will be applied,which is known to cause spectral leakage. Other windows such as torch.hann_window or torch.hamming_window can are recommended to reduce spectral leakage.To suppress this warning and use a rectangular window, explicitly set `window=torch.ones(n_fft, device=<device>)`. (Triggered internally at /opt/conda/conda-bld/pytorch_1720538440907/work/aten/src/ATen/native/SpectralOps.cpp:836.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]


torch.Size([1025, 1024])

In [12]:
n_fft = 2046
waveform_list_enhance = []
for waveform in waveform_list:
    hop_length = waveform.shape[-1]  // 1023
    waveform_list_enhance.append(torch.stft(waveform, n_fft = n_fft, hop_length= hop_length,return_complex=True)[:,0:1024])


/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/torch/functional.py:666: UserWarning: A window was not provided. A rectangular window will be applied,which is known to cause spectral leakage. Other windows such as torch.hann_window or torch.hamming_window can are recommended to reduce spectral leakage.To suppress this warning and use a rectangular window, explicitly set `window=torch.ones(n_fft, device=<device>)`. (Triggered internally at /opt/conda/conda-bld/pytorch_1720538440907/work/aten/src/ATen/native/SpectralOps.cpp:836.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]


In [13]:
for waveform in waveform_list_enhance:
    print(waveform.shape)

torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])
torch.Size([1024, 1024])


In [14]:
waveform_list_enhance[0].dtype

torch.complex64

In [15]:
waveform_tf_list = [torch.stack([waveform.real, waveform.imag],dim = 0).numpy() for waveform in waveform_list_enhance]

In [16]:
for waveform in waveform_tf_list:
    print(waveform.shape)

(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024, 1024)
(2, 1024

### 准备将预处理好的数据保存

In [3]:
NDARRAY_DIR = "/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray"
NDARRAY_TRAIN_DIR = join(NDARRAY_DIR,"train")

In [18]:
waveform_tf_raw_np = np.stack(arrays= waveform_tf_list, axis=0)

In [19]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"waveform_tf_raw.npz"),arr_0 = waveform_tf_raw_np)

### 由于 pytorch Dataset 无法装在形状不同的张量，因此将其经过预训练模型预处理后再保存。

#### 心理张量保存

In [12]:
from onnx2torch import convert
import onnx

emotion_model = onnx.load_model(r"/public1/cjh/workspace/DepressionPrediction/model/component/emotion_path/model/model.onnx")
emotion_model = convert(emotion_model)

In [15]:
emotion_model.to("cpu")

GraphModule(
  (ReduceMean_0): OnnxReduceStaticAxes()
  (Sub_1): OnnxBinaryMathOperation()
  (Mul_2): OnnxBinaryMathOperation()
  (ReduceMean_3): OnnxReduceStaticAxes()
  (Sub_4): OnnxBinaryMathOperation()
  (Constant_5): OnnxConstant()
  (Add_6): OnnxBinaryMathOperation()
  (Sqrt_7): OnnxSqrt()
  (Div_8): OnnxBinaryMathOperation()
  (Unsqueeze_9): OnnxUnsqueezeStaticAxes()
  (Conv_10): Conv1d(1, 512, kernel_size=(10,), stride=(5,))
  (Transpose_11): OnnxTranspose()
  (ReduceMean_12): OnnxReduceStaticAxes()
  (Sub_13): OnnxBinaryMathOperation()
  (Constant_14): OnnxConstant()
  (Pow_15): OnnxPow()
  (ReduceMean_16): OnnxReduceStaticAxes()
  (Constant_17): OnnxConstant()
  (Add_18): OnnxBinaryMathOperation()
  (Sqrt_19): OnnxSqrt()
  (Div_20): OnnxBinaryMathOperation()
  (initializers): Module()
  (Mul_21): OnnxBinaryMathOperation()
  (Add_22): OnnxBinaryMathOperation()
  (Transpose_23): OnnxTranspose()
  (Constant_24): OnnxConstant()
  (Div_25): OnnxBinaryMathOperation()
  (Erf_26): On

In [17]:
emotion_hiddenvecotr_list = []
for waveform in waveform_list:
    waveform = torch.unsqueeze(waveform,dim=0)
    emotion_hiddenvecotr_list.append(emotion_model(waveform)[0])
    

: 

In [7]:
data = np.load("/public1/cjh/workspace/DepressionPrediction/dataset/raw_ndarray/train/emotion_hiddenvec_raw.npz")["arr_0"]
data.shape

(249, 1024)

In [4]:
data = np.squeeze(data)
data.shape

(249, 1024)

In [6]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"emotion_hiddenvec_raw.npz"),arr_0 = data)

### 准备预处理文本向量

In [15]:
from sentence_transformers import SentenceTransformer
sbert =  SentenceTransformer("/public1/cjh/workspace/DepressionPrediction/model/pretrained_model/all-MiniLM-L12-v1",device="cuda:1")

/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
/public1/cjh/anaconda3/envs/depression/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [16]:
result = sbert.encode(text_list)

In [17]:
result.shape

(249, 384)

In [18]:
type(result)

numpy.ndarray

In [19]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"text_raw.npz"),arr_0 = result)

In [5]:
label_np = np.load(join(NDARRAY_TRAIN_DIR,"labels.npz"))["arr_0"]

In [7]:
label_np = label_np.astype(np.float32)

In [12]:
label_np.shape

(249, 1)

In [11]:
label_np = np.expand_dims(label_np, axis=-1)

In [13]:
np.savez_compressed(join(NDARRAY_TRAIN_DIR,"labels.npz"),arr_0 = label_np)